// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use env var if available, otherwise default for SQLite (needed for prisma generate on Vercel)
    url: process.env.DATABASE_URL || "file:./dev.db",
  },
});
