name: Issue
description: Create a new issue
title: "[Issue]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the issue
      placeholder: Describe the issue...
    validations:
      required: true

  - type: dropdown
    id: labels
    attributes:
      label: Labels
      description: Select the appropriate label for this issue
      options:
        - claude-triage
        - claude-implement
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the issue here
      placeholder: Additional information...
    validations:
      required: false
